language: java

jdk: oraclejdk10

before_install:
 - chmod +x gradlew

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_API_KEY
  file: "travis-ci-prototype.jar"
  on:
    tags: true